### ISSUE TITLE
iOS 13 detection issue

### ISSUE THREAD

**Issue by sesam** [bendrucker/is-ios#2]
5 years later: there's a new issue from iOS13 onwards. See https://stackoverflow.com/questions/9038625/detect-if-device-is-ios/9039885#9039885 for details.

PRs welcome? Would you cut a new version for this? (Otherwise I'll go package-less for this specific need.)

**Comment by bendrucker** [comment]
Yes please!

**Comment by sesam** [comment]
I've got code now that is now fairly well-tested, so will try to make a PR soon-ish.

**Comment by bendrucker** [comment]
Closed by #3
